export async function buildHoaPdfBytes(params: {
  letter: string;
  letterhead?: string;
  communityName?: string;
  logoUrl?: string | null;
}) {
  const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib");

  const pdfDoc = await PDFDocument.create();
  let page = pdfDoc.addPage([612, 792]); // US Letter
  const font = await pdfDoc.embedFont(StandardFonts.TimesRoman);
  const fontBold = await pdfDoc.embedFont(StandardFonts.TimesRomanBold);

  // Margins + layout similar to HOA templates
  const marginX = 72; // 1 inch
  const top = 740;
  let y = top;

  // Optional logo
  if (params.logoUrl) {
    try {
      const resp = await fetch(params.logoUrl);
      if (resp.ok) {
        const ab = await resp.arrayBuffer();
        const bytes = new Uint8Array(ab);
        // Try PNG first, fallback JPG
        let img: any = null;
        try { img = await pdfDoc.embedPng(bytes); } catch { img = await pdfDoc.embedJpg(bytes); }
        const dims = img.scale(1);
        const targetH = 48;
        const scale = targetH / dims.height;
        const w = dims.width * scale;
        page.drawImage(img, { x: marginX, y: y - targetH + 6, width: w, height: targetH });
      }
    } catch {}
  }

  // Letterhead block (right aligned-ish)
  const lh = (params.letterhead || "").trim();
  if (lh) {
    const lines = lh.split(/\r?\n/);
    const lhX = marginX + 240;
    let lhY = y;
    page.drawText(lines[0] || "", { x: lhX, y: lhY, size: 11, font: fontBold, color: rgb(0.12,0.12,0.12) });
    lhY -= 14;
    for (const line of lines.slice(1)) {
      page.drawText(line, { x: lhX, y: lhY, size: 10.5, font, color: rgb(0.18,0.18,0.18) });
      lhY -= 13;
    }
  }

  // Divider line
  y -= 62;
  page.drawLine({ start: { x: marginX, y }, end: { x: 612 - marginX, y }, thickness: 1, color: rgb(0.75,0.75,0.75) });
  y -= 26;

  // Title
  page.drawText("NOTICE OF VIOLATION (DRAFT)", { x: marginX, y, size: 12.5, font: fontBold, color: rgb(0.1,0.1,0.1) });
  y -= 18;

  // Community (if provided)
  if (params.communityName) {
    page.drawText(params.communityName, { x: marginX, y, size: 11, font, color: rgb(0.1,0.1,0.1) });
    y -= 18;
  }

  // Body with wrap
  const fontSize = 11.25
  const lineHeight = 15;
  const maxWidth = 612 - marginX * 2;

  const paragraphs = (params.letter || "").replace(/\r\n/g, "\n").split("\n");
  const wrapped: string[] = [];
  for (const p of paragraphs) {
    if (!p.trim()) { wrapped.push(""); continue; }
    const words = p.split(/\s+/);
    let line = "";
    for (const w of words) {
      const test = line ? `${line} ${w}` : w;
      const width = font.widthOfTextAtSize(test, fontSize);
      if (width <= maxWidth) line = test;
      else { if (line) wrapped.push(line); line = w; }
    }
    if (line) wrapped.push(line);
    wrapped.push("");
  }

  for (const ln of wrapped) {
    if (y < 90) {
      page = pdfDoc.addPage([612, 792]);
      y = top;
    }
    if (ln === "") { y -= lineHeight; continue; }
    page.drawText(ln, { x: marginX, y, size: fontSize, font, color: rgb(0.1,0.1,0.1) });
    y -= lineHeight;
  }

  // Footer
  const footerY = 46;
  page.drawLine({ start: { x: marginX, y: 60 }, end: { x: 612 - marginX, y: 60 }, thickness: 0.5, color: rgb(0.8,0.8,0.8) });
  page.drawText("Generated by HOA Letter AI • Draft for review • Not legal advice", { x: marginX, y: footerY, size: 9, font, color: rgb(0.45,0.45,0.45) });

  const bytes = await pdfDoc.save();
  return bytes; // Uint8Array
}
